### ISSUE TITLE
if set css:false in compilerOptions i get current error

### ISSUE THREAD

**Issue by timeshift92** [AlexxNB/svelte-esbuild-starter#1]
![image](https://user-images.githubusercontent.com/13614530/108879482-2153b900-7623-11eb-9b93-2ebcfc5ec8c3.png)

**Comment by AlexxNB** [comment]
Hmm.. `css` is `false` by default and works great. Please give me more info.

**Comment by AlexxNB** [comment]
Ah,ok... I just try to setup project from scratch and get this error... Will try to fix it. Thanks.

**Comment by AlexxNB** [comment]
The problem with esbuild-svelte plugin. I wrote issue to its repo  https://github.com/EMH333/esbuild-svelte/issues/33

**Comment by AlexxNB** [comment]
Now you can downgrade to esbuild@0.5.0 to temporally fix the problem.

**Comment by AlexxNB** [comment]
The problem is fixed in `esbuild-svelte`, so just run `npm i -D esbuild-svelte` to fix your issue.

**Comment by timeshift92** [comment]
Cool, thanks
